CREATE TABLE TABLE_PATIENT(
OBJID INT(11) PRIMARY KEY,
PATIENT_ID VARCHAR(25),
PATIENT_NAME VARCHAR(50),
MOBILE VARCHAR(20),
STATUS CHAR NOT NULL,
ADDRESS VARCHAR(300),
EFFECTIVE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIED_DATE DATETIME
);